name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Change to the version you're using

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Tests
      run: mvn test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

    - name: Upload JAR file
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/your-application.jar # Update with your application's JAR file

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

    - name: Upload Test Results to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
